### ISSUE TITLE
AWSCatalogMetastoreClient uses the wrong Glue Catalog ID when checking default database

### ISSUE THREAD

**Issue by rednaxelafx** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#12]
The constructor of `AWSCatalogMetastoreClient` (in both the Hive2 / Spark variants) checks the existence of the `default` database *before* assigning `this.catalogId`:
https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/blob/6b06b5a03a10633846fe30ce6d7de6964e6c5bf6/aws-glue-datacatalog-spark-client/src/main/java/com/amazonaws/glue/catalog/metastore/AWSCatalogMetastoreClient.java#L154-L157

But the `doesDefaultDBExist` uses `this.catalogId` when making the `databaseExists("default")` check.

When the user has specified a `"hive.metastore.glue.catalogid"` different from the default (the same ID as the current AWS account), the order above can be problematic: it'd (incorrectly) check the `default` database of the current AWS account, while all subsequent operations would use the user-specified account ID correctly.

This problem would block users from being able to use the client, when they don't have permissions to access the `default` database in the Glue Catalog of the same AWS account, but instead only have permissions to access the databases in the specified Glue Catalog account.

**Comment by aws-austin-lee** [comment]
I accepted your PR.  Thanks for making a contribution.

**Comment by rragundez** [comment]
I'm setting the correct configuration hive.metastore.client.factory.class": "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory", and  "hive.metastore.glue.catalogid" pointing to a different Account ID, but when I list databased only `default` appears, and not all my other databased. Can this issue be related to this behaviour?

**Comment by rednaxelafx** [comment]
@rragundez not from AWS but from my experience of using Glue, this may be related to how much permissions you've given to your access through the IAM permissions. If you only allow access on `catalog` and `database/default` then that's what you'll get.
