### ISSUE TITLE
Glue client jars in central mvn repository (https://mvnrepository.com/artifact/com.amazonaws)

### ISSUE THREAD

**Issue by shreya668** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#4]
Hi,
Are you guys planning to upload the glue client jars in the public artifactory ?

**Comment by aws-austin-lee** [comment]
Do you mean the Glue SDK?

https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-glue/1.11.182

**Comment by jricher-rms** [comment]
I think she means the hive and spark clients.

**Comment by aws-austin-lee** [comment]
No plans for this at the moment.
