### ISSUE TITLE
NullPointerException thrown from AWSCatalogMetastoreClient.getDatabases

### ISSUE THREAD

**Issue by youngbink** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#53]
Invocation of `AWSCatalogMetastoreClient.getDatabases` results in NullPointerException thrown from `AWSGlueMetastoreCacheDecorator.getAllDatabases`.

An example stacktrace:
> 

> Unable to get databases: 
java.lang.NullPointerException
	at com.amazonaws.glue.catalog.metastore.AWSGlueMetastoreCacheDecorator.getAllDatabases(AWSGlueMetastoreCacheDecorator.java:124)
	at com.amazonaws.glue.catalog.metastore.GlueMetastoreClientDelegate.getDatabases(GlueMetastoreClientDelegate.java:211)
	at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClient.getDatabases(AWSCatalogMetastoreClient.java:278)
	at org.apache.hadoop.hive.ql.metadata.Hive.getDatabasesByPattern(Hive.java:1273)
	at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$listDatabases$1(HiveClientImpl.scala:445)

I looked into this issue and this is caused by how it uses guava cache's `size` method [for checking whether it should pull from cache or not ](https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/blob/a934ecf07410b9f7519736450b6a4bd23d61b7cf/aws-glue-datacatalog-client-common/src/main/java/com/amazonaws/glue/catalog/metastore/AWSGlueMetastoreCacheDecorator.java#L120) before retrieving a cached entry using `getIfPresent`. 

Details: `size` method does not clear out expired entries, meaning that the result could also include expired entries. (Note that Guava cache doesn't clean up cache aggressively by default). This means that even when databases cache has its entry for `DATABASES_CACHE_KEY` expired, it can still return positive # of size, which would make `AWSGlueMetastoreCacheDecorator` to read from the cache. Then, `getIfPresent` for `DATABASES_CACHE_KEY` will return null as the entry has expired. Finally, [AWSGlueMetastoreCacheDecorator attempts to iterate on null](https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/blob/a934ecf07410b9f7519736450b6a4bd23d61b7cf/aws-glue-datacatalog-client-common/src/main/java/com/amazonaws/glue/catalog/metastore/AWSGlueMetastoreCacheDecorator.java#L124), triggering `NullPointerException`. 

Besides this problem caused by `size` including expired entries, another issue is that there can be a race condition so that the cached entry expire between check (`size`) and read (`getIfPresent`). When that happens, we could still run into `NullPointerException` even if `AWSGlueMetastoreCacheDecorator` cleared out expired entries before calling `size`.

**Comment by aws-austin-lee** [comment]
Change merged.  Thank you so much for your contribution.

**Comment by youngbink** [comment]
Thank you @aws-austin-lee !
