### ISSUE TITLE
Issues building hive for spark

### ISSUE THREAD

**Issue by stijndehaes** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#6]
I had some issues building the hive client for spark. I used this branch instead of the instructions: https://github.com/JoshRosen/hive/commits/release-1.2.1-spark2

Is that correct?

**Comment by aws-austin-lee** [comment]
Can you elaborate on the issues you ran into?

**Comment by tayler-jones** [comment]
This is correct: You can’t just use hive, it must be this specific fork as
it is what Spark uses. It’s a separate fork to skate around some Apache
project rules. It must of been cached in local repo if the build worked for
the original authors.

-TJ
