### ISSUE TITLE
AWSCatalogMetastoreClient regressed to using the wrong Glue Catalog ID when checking default database

### ISSUE THREAD

**Issue by cwienberg** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#68]
The previously resolved issue #12 was undone in 5e1546b. It is again the case that catalogId is being set for the AWSCatalogMetastoreClient after checking if the default DB exists, resulting in a default DB check being performed against the AWS account associated to the IAM identity accessing Glue, rather than the catalog that has been configured.

This issue impacts both the spark client and the hive3 client:
https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/blob/d4a6948514cb5acf3e3e4d8d9cb0969d07c8f61d/aws-glue-datacatalog-spark-client/src/main/java/com/amazonaws/glue/catalog/metastore/AWSCatalogMetastoreClient.java#L147-L151
https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/blob/d4a6948514cb5acf3e3e4d8d9cb0969d07c8f61d/aws-glue-datacatalog-hive3-client/src/main/java/com/amazonaws/glue/catalog/metastore/AWSCatalogMetastoreClient.java#L184-L188

The `doesDefaultDBExist` method references the `catalogId` instance variable, which is unset until after the check. Since it's null, the `doesDefaultDBExist` relies on a `null`, and therefore the account's default glue catalog. This check then fails if the IAM identity does not have permissions to the glue catalog in that identity's account, which is a reasonable choice if that identity is supposed to be querying an external catalog.

**Comment by cwienberg** [comment]
@aws-jeffrey-yang how should I follow up on this?

**Comment by aws-jeffrey-yang** [comment]
Thank you for catching that unfortunate regression
