### ISSUE TITLE
Not able to build aws-glue-datacatalog-hive2-client

### ISSUE THREAD

**Issue by vgthoppae** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#7]
So I'm looking to build only the hive2-client jar strictly following README.MD and the compilation fails because of the below reason. Yes, I have downloaded hive, switched to branch-2.3, applied the batch and built it. Am I missing something?

The dependency tree goes like this.
aws-glue-datacatalog-hive2-client
        |
        |
aws-glue-datacatalog-client-common
	|
	|
aws-glue-datacatalog-shims-loader
	|
	|
aws-glue-datacatalog-spark-hive-shims

``aws-glue-datacatalog-spark-hive-shims`` project defines dependency on the below missing jars with scope as provided, with no jars available at the compile time to resolve the dependencies.
``org.spark-project.hive.hive-exec-1.2.1.jar``
``org.spark-project.hive.hive-metastore-1.2.1.jar ``

**Comment by dacort** [comment]
@vgthoppae Try removing the dependency for `aws-glue-datacatalog-spark-client` in `aws-glue-datacatalog-hive2-client/pom.xml` to get the hive2-client to build. I believe that's in there for tests, but it's not required for functionality of the hive client.
